language: ruby
rvm:
  - "2.0.0"
  - "2.1.1"

matrix:
  include:
    - rvm: 2.1.0
      gemfile: gemfiles/rails4.gemfile
    - rvm: 1.9.3
      gemfile: gemfiles/rails4.gemfile

gemfile:
  - gemfiles/rails3.gemfile
  - gemfiles/rails4.gemfile
  - gemfiles/rails4.1.gemfile

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

script: 'COVERAGE=true rake spec:travis'

bundler_args: --without headless debug

before_install:
  - gem install bundler
